"""Desktop application boundary for ECatVASP."""

from ecatvasp.desktop.host import (
    DESKTOP_HOST_CONTRACT_VERSION,
    HOST_EXIT_BACKEND_FAILURE,
    HOST_EXIT_OK,
    DesktopHostErrorFrame,
    decode_versioned_desktop_request,
    encode_desktop_host_error,
    encode_versioned_desktop_response,
    run_stdio_host,
)
from ecatvasp.desktop.protocol import (
    DESKTOP_IPC_CONTRACT_VERSION,
    DesktopBackend,
    DesktopError,
    DesktopIPCError,
    DesktopOperation,
    DesktopRequest,
    DesktopResponse,
    decode_desktop_request,
    encode_desktop_response,
)
from ecatvasp.desktop.protocol_v2 import (
    DESKTOP_IPC_V2_CONTRACT_VERSION,
    DesktopBackendV2,
    DesktopV2ApplicationReportRequest,
    DesktopV2HealthRequest,
    DesktopV2Operation,
    DesktopV2PrepareWorkflowRequest,
    DesktopV2ProjectRequest,
    DesktopV2Request,
    DesktopV2Response,
    decode_desktop_v2_request,
    encode_desktop_v2_response,
)
from ecatvasp.desktop.workspace import DesktopProjectDashboard, build_desktop_project_dashboard

__all__ = [
    "DESKTOP_HOST_CONTRACT_VERSION",
    "DESKTOP_IPC_CONTRACT_VERSION",
    "DESKTOP_IPC_V2_CONTRACT_VERSION",
    "HOST_EXIT_BACKEND_FAILURE",
    "HOST_EXIT_OK",
    "DesktopBackend",
    "DesktopBackendV2",
    "DesktopError",
    "DesktopHostErrorFrame",
    "DesktopIPCError",
    "DesktopOperation",
    "DesktopProjectDashboard",
    "DesktopRequest",
    "DesktopResponse",
    "DesktopV2ApplicationReportRequest",
    "DesktopV2HealthRequest",
    "DesktopV2Operation",
    "DesktopV2PrepareWorkflowRequest",
    "DesktopV2ProjectRequest",
    "DesktopV2Request",
    "DesktopV2Response",
    "build_desktop_project_dashboard",
    "decode_desktop_request",
    "decode_desktop_v2_request",
    "decode_versioned_desktop_request",
    "encode_desktop_host_error",
    "encode_desktop_response",
    "encode_desktop_v2_response",
    "encode_versioned_desktop_response",
    "run_stdio_host",
]
