"""Execution-layer provenance, target, runtime, and adapter contracts for ECatVASP."""

from ecatvasp.execution.adapters import (
    CommandResult,
    CommandSpec,
    SchedulerAdapter,
    SchedulerObservation,
    SchedulerSubmission,
    TargetRelativePath,
    TransportAdapter,
    validate_adapter_target,
)
from ecatvasp.execution.local import LocalExecutionError, LocalExecutionResult, LocalExecutor
from ecatvasp.execution.monitoring import (
    ExecutionMonitoringError,
    SlurmMonitoringPackage,
    VaspRuntimeProgress,
    cancel_remote_slurm,
    monitor_remote_slurm,
    probe_vasp_runtime_progress,
)
from ecatvasp.execution.provenance import (
    ExecutionProvenanceError,
    create_execution_attempt,
    validate_execution_attempt_plan,
)
from ecatvasp.execution.recovery import (
    ExecutionEvidence,
    RecoveryAction,
    RecoveryCause,
    RecoveryChangeLayer,
    RecoveryClassificationError,
    RecoveryDecision,
    RecoveryRequest,
    classify_recovery,
    create_recovery_execution_attempt,
    derive_execution_recovery_plan,
)
from ecatvasp.execution.remote import (
    RemotePotcarLibrary,
    RemoteStageFileRecord,
    RemoteStageManifest,
    RemoteStagePackage,
    RemoteStagingError,
    stage_remote_runtime,
)
from ecatvasp.execution.retrieval import (
    RemoteRetrievalPackage,
    RetrievalError,
    RetrievalFileRecord,
    RetrievalManifest,
    retrieve_remote_outputs,
)
from ecatvasp.execution.runtime import (
    LocalPotcarResolution,
    LocalRuntimePackage,
    RuntimeFileRecord,
    RuntimeInputManifest,
    RuntimeMaterializationError,
    materialize_local_runtime,
)
from ecatvasp.execution.slurm import (
    ResolvedSchedulerResources,
    SlurmAdapter,
    SlurmJobScript,
    SlurmObservationError,
    SlurmSubmissionError,
    SlurmSubmissionPackage,
    render_slurm_job_script,
    resolve_scheduler_resources,
    submit_remote_slurm,
)
from ecatvasp.execution.ssh import (
    OpenSshTransport,
    OpenSshTransportError,
    remote_absolute_path,
)
from ecatvasp.execution.targets import (
    ExecutionEnvironmentSnapshot,
    ExecutionTargetProfile,
    SshSecurityPolicy,
    TransportKind,
)

__all__ = [
    "CommandResult",
    "CommandSpec",
    "ExecutionEnvironmentSnapshot",
    "ExecutionEvidence",
    "ExecutionMonitoringError",
    "ExecutionProvenanceError",
    "ExecutionTargetProfile",
    "LocalExecutionError",
    "LocalExecutionResult",
    "LocalExecutor",
    "LocalPotcarResolution",
    "LocalRuntimePackage",
    "OpenSshTransport",
    "OpenSshTransportError",
    "RecoveryAction",
    "RecoveryCause",
    "RecoveryChangeLayer",
    "RecoveryClassificationError",
    "RecoveryDecision",
    "RecoveryRequest",
    "RemotePotcarLibrary",
    "RemoteRetrievalPackage",
    "RemoteStageFileRecord",
    "RemoteStageManifest",
    "RemoteStagePackage",
    "RemoteStagingError",
    "ResolvedSchedulerResources",
    "RetrievalError",
    "RetrievalFileRecord",
    "RetrievalManifest",
    "RuntimeFileRecord",
    "RuntimeInputManifest",
    "RuntimeMaterializationError",
    "SchedulerAdapter",
    "SchedulerObservation",
    "SchedulerSubmission",
    "SlurmAdapter",
    "SlurmJobScript",
    "SlurmMonitoringPackage",
    "SlurmObservationError",
    "SlurmSubmissionError",
    "SlurmSubmissionPackage",
    "SshSecurityPolicy",
    "TargetRelativePath",
    "TransportAdapter",
    "TransportKind",
    "VaspRuntimeProgress",
    "cancel_remote_slurm",
    "classify_recovery",
    "create_execution_attempt",
    "create_recovery_execution_attempt",
    "derive_execution_recovery_plan",
    "materialize_local_runtime",
    "monitor_remote_slurm",
    "probe_vasp_runtime_progress",
    "remote_absolute_path",
    "render_slurm_job_script",
    "resolve_scheduler_resources",
    "retrieve_remote_outputs",
    "stage_remote_runtime",
    "submit_remote_slurm",
    "validate_adapter_target",
    "validate_execution_attempt_plan",
]
