"""Structure import, identity, and construction boundary."""

from ecatvasp.structures.addition import (
    AtomAdditionAction,
    AtomAdditionLineageEvent,
    StructureAdditionError,
    StructureAdditionResult,
    append_structure_sites,
)
from ecatvasp.structures.graphene import GrapheneBuildSpec, build_graphene
from ecatvasp.structures.identity import (
    AtomIdentityMapping,
    AtomMappingEntry,
    AtomMappingError,
    AtomMappingMethod,
    GeometrySite,
    IdentityPropagationResult,
    propagate_atom_uids_by_index,
    reconcile_reordered_sites,
    reorder_snapshot,
    validate_identity_preserving_revision,
)
from ecatvasp.structures.io import (
    AtomIdentityStatus,
    SelectiveDynamics,
    StructureDocument,
    StructureFormat,
    StructureIOError,
    StructureSourceMetadata,
    export_structure,
    import_structure,
    parse_structure,
    serialize_structure,
)
from ecatvasp.structures.multi_metal import (
    EnsembleSideTopology,
    MetalPairDistance,
    MultiMetalCenterResult,
    MultiMetalCenterSpec,
    MultiMetalSiteError,
    MultiMetalSiteResult,
    MultiMetalSiteSpec,
    build_multi_metal_site,
    derive_side_topology,
)
from ecatvasp.structures.mutation import (
    AtomLineageAction,
    AtomLineageEvent,
    DopantSubstitution,
    StructureMutationError,
    StructureMutationResult,
    mutate_structure,
    remove_vacancies,
    substitute_dopants,
)
from ecatvasp.structures.single_metal import (
    SingleMetalSiteError,
    SingleMetalSiteResult,
    SingleMetalSiteSpec,
    build_single_metal_site,
)

__all__ = [
    "AtomAdditionAction",
    "AtomAdditionLineageEvent",
    "AtomIdentityMapping",
    "AtomIdentityStatus",
    "AtomLineageAction",
    "AtomLineageEvent",
    "AtomMappingEntry",
    "AtomMappingError",
    "AtomMappingMethod",
    "DopantSubstitution",
    "EnsembleSideTopology",
    "GeometrySite",
    "GrapheneBuildSpec",
    "IdentityPropagationResult",
    "MetalPairDistance",
    "MultiMetalCenterResult",
    "MultiMetalCenterSpec",
    "MultiMetalSiteError",
    "MultiMetalSiteResult",
    "MultiMetalSiteSpec",
    "SelectiveDynamics",
    "SingleMetalSiteError",
    "SingleMetalSiteResult",
    "SingleMetalSiteSpec",
    "StructureAdditionError",
    "StructureAdditionResult",
    "StructureDocument",
    "StructureFormat",
    "StructureIOError",
    "StructureMutationError",
    "StructureMutationResult",
    "StructureSourceMetadata",
    "append_structure_sites",
    "build_graphene",
    "build_multi_metal_site",
    "build_single_metal_site",
    "derive_side_topology",
    "export_structure",
    "import_structure",
    "mutate_structure",
    "parse_structure",
    "propagate_atom_uids_by_index",
    "reconcile_reordered_sites",
    "remove_vacancies",
    "reorder_snapshot",
    "serialize_structure",
    "substitute_dopants",
    "validate_identity_preserving_revision",
]
