"""VASP-facing adapters that preserve ECatVASP domain boundaries."""

from ecatvasp.vasp.contracts import (
    ECATVASP_ECAT_STANDARD,
    ECATVASP_ECAT_STANDARD_EDIFFG_EV_PER_ANGSTROM,
    LatticeAxis,
    ProjectNumericalLock,
    VaspSystemContext,
    VaspSystemKind,
)
from ecatvasp.vasp.importer import (
    ExistingVaspImport,
    ParsedVaspResult,
    VaspFolderInspection,
    VaspImportError,
    import_existing_vasp_folder,
    inspect_vasp_folder,
)
from ecatvasp.vasp.recipes import (
    RECIPE_ADSORBATE_RELAX,
    RECIPE_CHARGE_DENSITY_STATIC,
    RECIPE_DOS_PREREQUISITE,
    RECIPE_ENCUT_CONVERGENCE_POINT,
    RECIPE_FULL_FREQUENCY,
    RECIPE_GAS_FREQUENCY,
    RECIPE_GAS_RELAX,
    RECIPE_GROUND_STATE_STATIC,
    RECIPE_KPOINT_CONVERGENCE_POINT,
    RECIPE_LOBSTER_PREREQUISITE,
    RECIPE_SELECTED_ATOM_FREQUENCY,
    RECIPE_SLAB_RELAX,
    VASP_RECIPE_REGISTRY,
    VASP_RECIPE_SPECS,
    VaspRecipeContractError,
    VaspRecipeSpec,
    get_vasp_recipe_spec,
    validate_calculation_recipe_contract,
)

__all__ = [
    "ECATVASP_ECAT_STANDARD",
    "ECATVASP_ECAT_STANDARD_EDIFFG_EV_PER_ANGSTROM",
    "ExistingVaspImport",
    "LatticeAxis",
    "ParsedVaspResult",
    "ProjectNumericalLock",
    "RECIPE_ADSORBATE_RELAX",
    "RECIPE_CHARGE_DENSITY_STATIC",
    "RECIPE_DOS_PREREQUISITE",
    "RECIPE_ENCUT_CONVERGENCE_POINT",
    "RECIPE_FULL_FREQUENCY",
    "RECIPE_GAS_FREQUENCY",
    "RECIPE_GAS_RELAX",
    "RECIPE_GROUND_STATE_STATIC",
    "RECIPE_KPOINT_CONVERGENCE_POINT",
    "RECIPE_LOBSTER_PREREQUISITE",
    "RECIPE_SELECTED_ATOM_FREQUENCY",
    "RECIPE_SLAB_RELAX",
    "VASP_RECIPE_REGISTRY",
    "VASP_RECIPE_SPECS",
    "VaspFolderInspection",
    "VaspImportError",
    "VaspRecipeContractError",
    "VaspRecipeSpec",
    "VaspSystemContext",
    "VaspSystemKind",
    "get_vasp_recipe_spec",
    "import_existing_vasp_folder",
    "inspect_vasp_folder",
    "validate_calculation_recipe_contract",
]
